- name: "Table Surface"
  remove_surface: true
  parent_frame_id: "table_base_link"
  child_frame_id: "camera_link"
  bounding_frame_id: "table_base_link"
  segmentation_frame_id: "table_base_link"
  x_min: -0.65
  x_max: 0.7
  y_min: 0.05
  y_max: 0.825
  z_min: -0.2